' Developer Express Code Central Example:
' How to calculate multiple Custom Totals with SummaryType set to Custom
' 
' The following example demonstrates how to calculate and display multiple Custom
' Totals for a field.
' 
' In this example, two Custom Totals are implemented for
' the Category Name field. The first one displays a median calculated against
' summary values, while the second one displays the first and third
' quartiles.
' 
' To accomplish this task, we create two PivotGridCustomTotal
' objects and set their summary type to PivotSummaryType.Custom. We also assign
' the Custom Totals' names to PivotGridCustomTotalBase.Tag properties to be able
' to distinguish between the Custom Totals when we calculate their values.
' Finally, we add the created objects to the Category Name field's
' PivotGridField.CustomTotals collection and enable the Custom Totals to be
' displayed for this field by setting the PivotGridFieldBase.TotalsVisibility
' property to PivotTotalsVisibility.CustomTotals.
' 
' Custom Total values are
' actually calculated in the PivotGridControl.CustomCellValue event. First, the
' event handler prepares a list of summary values against which a Custom Total
' will be calculated. For this purpose, it creates a summary datasource and copies
' the summary values to an array. After that, the array is sorted and passed to an
' appropriate method that calculates a median or quartile value against the
' provided array. Finally, the resulting value is assigned to the event
' parameter's PivotCellValueEventArgs.Value property.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E3815

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
Namespace My


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
	Friend Class Resources

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property
	End Class
End Namespace
