// Developer Express Code Central Example:
// How to calculate multiple Custom Totals with SummaryType set to Custom
// 
// The following example demonstrates how to calculate and display multiple Custom
// Totals for a field.
// 
// In this example, two Custom Totals are implemented for
// the Category Name field. The first one displays a median calculated against
// summary values, while the second one displays the first and third
// quartiles.
// 
// To accomplish this task, we create two PivotGridCustomTotal
// objects and set their summary type to PivotSummaryType.Custom. We also assign
// the Custom Totals' names to PivotGridCustomTotalBase.Tag properties to be able
// to distinguish between the Custom Totals when we calculate their values.
// Finally, we add the created objects to the Category Name field's
// PivotGridField.CustomTotals collection and enable the Custom Totals to be
// displayed for this field by setting the PivotGridFieldBase.TotalsVisibility
// property to PivotTotalsVisibility.CustomTotals.
// 
// Custom Total values are
// actually calculated in the PivotGridControl.CustomCellValue event. First, the
// event handler prepares a list of summary values against which a Custom Total
// will be calculated. For this purpose, it creates a summary datasource and copies
// the summary values to an array. After that, the array is sorted and passed to an
// appropriate method that calculates a median or quartile value against the
// provided array. Finally, the resulting value is assigned to the event
// parameter's PivotCellValueEventArgs.Value property.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E3815

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtraPivotGrid_MultipleCustomTotals.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\nwind.mdb;Persist Se" +
            "curity Info=True")]
        public string nwindConnectionString {
            get {
                return ((string)(this["nwindConnectionString"]));
            }
        }
    }
}
